core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('registration/', include('django.contrib.auth.urls')),
    # path('dashboard/', include('dashboard.urls')),

    # path('basket/', include('basket.urls', namespace='basket')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('checkout/', include('checkout.urls')),
    # path('orders/', include('orders.urls')),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.all_products, name='all_products'),
    path('single_product/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('product_create', views.product_create, name='product_create'),
    path('product_details/<int:pk>', views.product_detail, name='product_details'),
    path('product_update/<int:pk>', views.product_update, name='product_update'),
    path('product_delete/<int:pk>', views.product_delete, name='product_delete'),

    path('category/', views.all_categories, name='all_categories'),
    path('category_list_admin', views.category_list_admin, name="category_list_admin"),
    path('product_list_admin', views.product_list_admin, name="product_list_admin"),
    path('cart_list_admin', views.cart_list_admin, name="cart_list_admin"),
    path('cart_details_admin/<int:pk>', views.cart_details_admin, name="cart_details_admin"),

    path('add_to_cart/<int:product_id>/', views.add_to_cart, name="add_to_cart"),
    path('cart_summary/', views.cart_summary, name="cart_summary"),
    path('cart_success/', views.cart_success, name="cart_success"),

    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('category_details/<slug:category_slug>/', views.category_details, name='category_details'),
    path('category_create', views.category_create, name='category_create'),
    path('category_update/<int:pk>', views.category_update, name='category_update'),
    path('category_delete/<int:pk>', views.category_delete, name="category_delete"),

    path('design_inspiration/', views.design_inspiration, name='design_inspiration'),

    path('furniture/', views.furniture, name='furniture'),
    path('accesories/', views.accesories, name='accesories'),

    path('registration/', views.registration, name='registration'),
    # path('registration/login/', auth_views.LoginView.as_view(template_name='registration/login.html')),
    # path('register', views.user_create_by_form, name='register'),

    # path('searchbox/', views.Searchbox, name='searchbox'),
]

store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to='images/', default=True)
    parent = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'categories'

    # functia care returneaza url-ul de single page
    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)
    category = models.ForeignKey(Category, related_name='product', on_delete=models.SET_NULL, null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    stock = models.IntegerField()
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    status=models.CharField (max_length=30)


class Cartitem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

class CustomerDetail(models.Model):
    address1=models.CharField( max_length=255)
    address2=models.CharField( max_length=255)
    payment_option=models.CharField( max_length=50)
    User=models.OneToOneField(User, on_delete=models.CASCADE)

store/forms.py
from django import forms
from django import forms
from django.contrib.auth.models import User

class ProductCreate(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"


# class UserCreate(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ['username', "email", "password", "first_name", "last_name"]

store/views.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect

from .models import Category, Product, Cart, Cartitem, CustomerDetail


def categories(request):
    return {
        'categories': Category.objects.all()
    }


def home(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'home.html', {'categories': categories, 'products': products, 'is_logged_in':is_logged_in})


# PRODUCTS
def all_products(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'store/products/product_list.html', {'categories': categories, 'products': products, 'is_logged_in':is_logged_in})


def product_detail(request, product_slug=None):
    product = get_object_or_404(Product, slug=product_slug, in_stock=True)
    is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'store/products/single_product.html', {'product': product, 'is_logged_in':is_logged_in})


def product_create(request):
    if request.method == "POST":
        name = request.POST.get('product_name', '')
        price = request.POST.get('product_price', '')
        stock = request.POST.get('product_stock', '')
        description = request.POST.get('product_description', '')
        category_id = request.POST.get('product_category_id', '')
        Product.objects.create(name=name,
                               price=price,
                               stock=stock,
                               description=description,
                               category_id=category_id)
        # return reverse_lazy('product_list')
        is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'store/products/product_create.html',
                  context={'categories': Category.objects.all(), 'is_logged_in':is_logged_in})


def product_update(request, pk):
    if request.method == "POST":
        id_ = request.POST.get('product_id', '')
        name = request.POST.get('product_name', '')
        price = request.POST.get('product_price', '')
        stock = request.POST.get('product_stock', '')
        description = request.POST.get('product_description', '')
        category_id = request.POST.get('product_category_id', '')
        product = Product.objects.get(id=id_)
        product.name = name
        product.description = description
        product.stock = stock
        product.price = price
        product.category_id = category_id
        product.save()
        return redirect('category_product')

    product = Product.objects.get(pk=pk)
    categories = Category.objects.all()
    is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'store/products/product_update.html', {'product': product, 'categories': categories, 'is_logged_in':is_logged_in})


def product_delete(request, pk):
    if request.method == "POST":
        id_ = request.POST.get('product_id', '')
        product = Product.objects.get(id=id_)
        product.delete()

        return redirect('category_product')
    product = Product.objects.get(id=pk)
    is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'store/products/product_delete.html', {'product': product, 'is_logged_in':is_logged_in})


def product_list_admin(request):
    products = Product.objects.all()
    is_logged_in = request.user is not None and not request.user.is_anonymous
    # products = Product.objects.filter(category=categories)
    return render(request, 'store/products/product_view_admin.html', {'products': products, 'is_logged_in':is_logged_in})


# CATEGORIES

def all_categories(request):
    categories = Category.objects.all()
    is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'store/category/category_list.html', {'categories': categories, 'is_logged_in':is_logged_in})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'store/category/category_list.html', {'category': category, 'products': products, 'is_logged_in':is_logged_in})


def category_details(request, category_slug=None):
    # category = get_object_or_404(Category, slug=category_slug, )

    category = Category.objects.get(slug=category_slug)
    products = Product.objects.filter(category_id=category.id)
    is_logged_in = request.user is not None and not request.user.is_anonymous
    print(len(products))
    return render(request, 'store/category/category_details.html', {'category': category, 'products': products,'is_logged_in':is_logged_in })


def category_create(request):
    context = {}
    error_msgs = []
    if request.method == "POST":
        print(request.POST)
        name = request.POST.get('category_name', '')

        existing_categories = Category.objects.filter(name__exact=name)
        if len(existing_categories) > 0:
            error_msgs.append('Category name exists! Please choose another name!')
        elif not name:
            error_msgs.append('Name is mandatory!')
        else:
            Category.objects.create(name=name)
            context['success_msg'] = 'Category added successfully!'
        if error_msgs:
            context['error_msgs'] = error_msgs
    is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'store/category/category_create.html',{'context':context, 'is_logged_in':is_logged_in})


def category_update(request, pk):
    context = {}
    error_msgs = []
    if request.method == "POST":
        id_ = request.POST.get('category_id', '')
        name = request.POST.get('category_name', '')
        existing_categories = Category.objects.filter(name__exact=name).exclude(id=id_)
        if len(existing_categories) > 0:
            error_msgs.append('Category name exists! Please choose another name!')
        elif not name:
            error_msgs.append('Name is mandatory!')
        else:
            category = Category.objects.get(id=id_)
            category.name = name
            category.save()
            context['success_msg'] = 'Category updated successfully!'
    context['category'] = Category.objects.get(id=pk)
    is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'store/category/category_update.html', {'context':context, 'is_logged_in':is_logged_in})


def category_delete(request, pk):
    if request.method == "POST":
        id_ = request.POST.get('category_id', '')
        category = Category.objects.get(id=id_)
        category.delete()
        return redirect('store:category_list')
    category = Category.objects.get(id=pk)
    is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'store/category/category_delete.html', {'category': category, 'is_logged_in':is_logged_in})


def category_list_admin(request):
    categories = Category.objects.all()
    # products = Product.objects.filter(category=categories)
    is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'store/category/category_view_admin.html', {'categories': categories, 'is_logged_in':is_logged_in})


# CART

def add_to_cart(request, product_id):
    user = request.user
    carts = Cart.objects.filter(user=user, status='open')
    if len(carts) == 0:
        cart = Cart.objects.create(user=user, status='open')
    else:
        cart = carts[0]
    cart_items = Cartitem.objects.filter(cart=cart, product_id=product_id)
    if len(cart_items) == 0:
        cart_item = Cartitem.objects.create(product_id=product_id, cart=cart, quantity=1)
    else:
        cart_item = cart_items[0]
        cart_item.quantity += 1
        cart_item.save()
    return redirect('store:cart_summary',)


def remove_from_cart(request, product_id):
    return redirect('/')


def cart_summary(request):
    user = request.user
    carts = Cart.objects.filter(user=user, status='open')
    if len(carts) == 0:
        cart = Cart.objects.create(user=user, status='open')
    else:
        cart = carts[0]
    if request.method == "POST":
        cart_item_id = request.POST.get('cart_item_id', '')
        quantity = request.POST.get('quantity', '')
        cart_item = Cartitem.objects.get(id=cart_item_id)
        cart_item.quantity = quantity
        cart_item.save()
    cart_items = Cartitem.objects.filter(cart=cart, )
    sum = 0
    for cart_item in cart_items:
        sum += cart_item.quantity * cart_item.product.price
    is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'store/cart/cart_summary.html', {'cart': cart, 'cart_items': cart_items, 'cart_total': sum, 'is_logged_in':is_logged_in},)


def cart_list_admin(request):
    if request.method == 'POST':
        print(request.POST)
        cart_id = request.POST.get('cart_id', '')
        cart = Cart.objects.get(id=cart_id)
        cart.status = 'shipped'
        cart.save()
    carts = Cart.objects.all()
    # products = Product.objects.filter(category=categories)
    is_logged_in = request.user is not None and not request.user.is_anonymous
    return render(request, 'store/cart/cart_view_admin.html', {'carts': carts, 'is_logged_in':is_logged_in})


def cart_details_admin(request, pk):
    cart = Cart.objects.get(id=pk)
    cart_items = Cartitem.objects.filter(cart=cart)
    is_logged_in = request.user is not None and not request.user.is_anonymous

templates/store/category/category_create.html
{% extends 'base.html' %}
{% block content %}
    <form class="menu_item" action="" method="post">
        {% csrf_token %}
        <label for="category_name">Category name:</label>
        <input id="category_name" type="text" name="category_name">
        <br>
        <input type="submit" value="Add Category">
    </form>
{% endblock content%}

templates/store/category/category_delete.html
{% extends 'base.html' %}
{% block content %}

    <h2>Do you want to delete {{ category.name }}?</h2>
    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="category_id" value="{{ category.id }}">
        <input type="submit" value="Delete category">
    </form>
{% endblock content %}

templates/store/category/category_details.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ category.name }}
{% endblock %}

{% block content %}
    <div class="container mx-25">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mx-2 my-2">
            {% for product in products %}


                <div class="col">
                    <div class="card shadow-sm">
                        <img src="{{ product.image.url }}">
                        <div class="card-body">
                            <p class="card-text"> {{ product.name }}</p>
                            <p class="card-text"> Price: {{ product.price }} € </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'store:product_detail' product_slug=product.slug %}" type="button"
                                       class="btn btn-sm btn-outline-warning">View details</a>
                                </div>

                                <form method="post" action="{% url 'store:add_to_cart'  product_id=product.id %}">
                                    {% csrf_token %}

                                    <button type="submit" class="btn btn-sm btn-warning">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor"
                                             class="bi bi-cart2" viewBox="0 0 16 16">
                                            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"></path>
                                        </svg>
                                        Add to cart
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>



{% endblock %}

templates/store/category/category_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <div class="container mx-25">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mx-2 my-2">
            {% for category in categories %}
                {% if not category.parent %}
                    <div class="col-md-5">
                        <div class="card shadow-sm">
                            <img src="{{ category.image.url }}">
                            <div class="card-body">
                                <p class="card-text"> {{ category.name }}.</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{% url 'store:category_list' category_slug=category.slug %}"
                                           type="button"
                                           class="btn btn-sm btn-outline-warning">View details</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/store/category/category_update.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="category_id" value="{{ category.id }}">
        <br>
        <br>
        <label for="category_name_input">Category name:</label>
        <input id="category_name_input" type="text" value='{{ category.name }}' name="category_name">
        <br>
        <br>
        <input type="submit" value="Update Category">
    </form>
{% endblock content %}

templates/store/category/category_view_admin.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}

    <div class="container mx-25">
    <div class="d-grid gap-2">
        <div class="btn-group">
            <a href="{% url 'store:category_create' %}" type="button"
               class="btn btn-sm btn-outline-warning">Add Category</a>
        </div>
    </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mx-2 my-2">
            {% for category in categories %}
                <div class="col">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="card shadow-sm">
                        <img src="{{ category.image.url }}">
                        <div class="card-body">
                            <p class="card-text"> {{ category.name }}</p>
                        </div>

                        <div class="btn-group">
                            <a href="{% url 'store:category_update' pk=category.id %}" type="button"
                               class="btn btn-sm btn-outline-warning">Update</a>
                        </div>

                        <div class="btn-group">
                            <a href="{% url 'store:category_delete' pk=category.id %}" type="button"
                               class="btn btn-sm btn-outline-warning">Delete</a>
                        </div>
                    </div>

                </div>
                </div>
            {% endfor %}
        </div>
    </div>

                {#                <div class="card-body">#}
                {#                    <p class="card-text"> {{ category.name }}.</p>#}
                {#                    <div class="d-flex justify-content-between align-items-center">#}
                {#                        <div class="btn-group">#}
                {#                            <a href="{% url 'store:category_update' pk=category.id %}" type="button"#}
                {#                               class="btn btn-sm btn-outline-warning">Update</a>#}
                {#                        </div>#}
                {#                    </div>#}
                {#                    <div class="d-flex justify-content-between align-items-center">#}
                {#                        <div class="btn-group">#}
                {#                            <a href="{% url 'store:category_delete' pk=category.id %}" type="button"#}
                {#                               class="btn btn-sm btn-outline-warning">Delete</a>#}
                {#                        </div>#}
                {#                    </div>#}
                {#                    <div class="d-flex justify-content-between align-items-center">#}
                {#                        <div class="btn-group">#}
                {#                            <a href="{% url 'store:category_list' category_slug=category.slug %}" type="button"#}
                {#                               class="btn btn-sm btn-outline-warning">View details</a>#}
                {#                        </div>#}
                {#                    </div>#}
                {##}
                {#                </div>#}




{#                {% if not category.parent %}#}
{#                    <div class="col-md-5">#}
{#                        <div class="card shadow-sm">#}
{#                            <img src="{{ category.image.url }}">#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="card-body">#}
{#                        <p class="card-text"> {{ category.name }}.</p>#}
{##}
{#                    </div>#}
{#                {% endif %}#}



{% endblock %}

templates/store/category/single_category.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ category.name }}
{% endblock %}

{% block content %}

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mx-2 my-2">
        {% for category.parent in categories %}

            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ product.image.url }}">
                    <div class="card-body">
                        <p class="card-text"> {{ product.title }}.</p>
                        <p class="card-text"> Price: {{ product.price }} € </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'store:product_detail' product_slug=product.slug %}" type="button"
                                   class="btn btn-sm btn-outline-warning">View details</a>
                            </div>

                            <form method="post" action="{% url 'store:add_to_cart'  product_id=product.id %}">
                                {% csrf_token %}

                                <button type="submit" class="btn btn-sm btn-warning">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-cart2" viewBox="0 0 16 16">
                                        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"></path>
                                    </svg>
                                    Add to cart
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        {% endfor %}
    </div>
{% endblock %}