core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('registration/', include('django.contrib.auth.urls')),
    # path('dashboard/', include('dashboard.urls')),

    # path('basket/', include('basket.urls', namespace='basket')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('checkout/', include('checkout.urls')),
    # path('orders/', include('orders.urls')),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.all_products, name='all_products'),
    path('single_product/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('product_create', views.product_create, name='product_create'),
    path('product_details/<int:pk>', views.product_detail, name='product_details'),
    path('product_update/<int:pk>', views.product_update, name='product_update'),
    path('product_delete/<int:pk>', views.product_delete, name='product_delete'),

    path('category/', views.all_categories, name='all_categories'),
    path('category_list_admin', views.category_list_admin, name="category_list_admin"),
    path('product_list_admin', views.product_list_admin, name="product_list_admin"),
    path('cart_list_admin', views.cart_list_admin, name="cart_list_admin"),
    path('cart_details_admin/<int:pk>', views.cart_details_admin, name="cart_details_admin"),

    path('add_to_cart/<int:product_id>/', views.add_to_cart, name="add_to_cart"),
    path('cart_summary/', views.cart_summary, name="cart_summary"),
    path('cart_success/', views.cart_success, name="cart_success"),

    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('category_details/<slug:category_slug>/', views.category_details, name='category_details'),
    path('category_create', views.category_create, name='category_create'),
    path('category_update/<int:pk>', views.category_update, name='category_update'),
    path('category_delete/<int:pk>', views.category_delete, name="category_delete"),

    path('design_inspiration/', views.design_inspiration, name='design_inspiration'),

    path('furniture/', views.furniture, name='furniture'),
    path('accesories/', views.accesories, name='accesories'),

    path('registration/', views.registration, name='registration'),
    # path('registration/login/', auth_views.LoginView.as_view(template_name='registration/login.html')),
    # path('register', views.user_create_by_form, name='register'),

    # path('searchbox/', views.Searchbox, name='searchbox'),
]

templates/Searchbox.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Searchbox{% endblock %}


{% block content %}

<form class="search" action="{% url 'search' %}" method='post'>
  {% csrf_token %}
  <input type="search" placeholder="Search here..." name="usr_query"
      value='{{ query }}' required>
  <button type="submit">Search</button>
</form>


    <h1>Search Result</h1>
    <ul>
        {% for product in products %}
        <li>
          {{ product.name }}, {{ product.price }}
        </li>
        {% endfor %}
    </ul>



{% endblock %}

templates/accesories.html
{% extends "base.html" %}
{% load static %}

{% block title %}Accesories{% endblock %}


{% block content %}


<div class="container-fluid">
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {% for subcategory in categories %}
            {% if subcategory.parent.id == category.id %}
                <li><a class="dropdown-item" id="submeniu"
                       href="#">{{ subcategory.name }}</a></li>
            {% endif %}

        {% endfor %}
      </ul>
</div>

    {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/6a23276998.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
<div id="pagina" class="row" style=display:block>


    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark mx-25px">
        <div class="container-fluid">
            <a href="/media/images/Rafa-kids_logo.png">
                <img src="http://127.0.0.1:8000/media/images/Rafa-kids_logo.png" class="nm-logo mx-2" alt="Rafa-Kids"
                     width="50px"
                     height="50px">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    {% if request.user.is_superuser %}

                        <li class="nav-item">
                            <a href="{% url 'store:category_list_admin' %}" class="nav-link nowrap">
                                Category List</a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'store:product_list_admin' %}" class="nav-link nowrap">
                                Product List</a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'store:cart_list_admin' %}" class="nav-link nowrap">
                                Cart List</a>
                        </li>

                    {% else %}
                        {% for category in categories %}
                            {% if not category.parent %}

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle nowrap" href="#"
                                       id="navbarDropdownMenuLink" role="button"
                                       data-bs-toggle="dropdown" aria-expanded="false">
                                        {{ category.name }}

                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        {% for subcategory in categories %}
                                            {% if subcategory.parent.id == category.id %}
                                                <li><a class="dropdown-item" id="submeniu"
                                                       href="{% url 'store:category_details' category_slug=subcategory.slug %}">{{ subcategory.name }}</a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endif %}

                        {% endfor %}
                        <li class="nav-item">
                            <a href="{% url 'store:design_inspiration' %}" class="nav-link nowrap">Design
                                Inspiration</a>
                        </li>
                    {% endif %}
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2 col-3 nowrap" type="search" placeholder="Search"
                           aria-label="Search">

                </form>

                {% if is_logged_in %}
                    <a href="{% url 'logout' %}" class="btn btn-outline-warning mx-2 nowrap" >Log out</a>
                {% else %}
                    <a href="{% url 'store:registration' %}" class="btn btn-outline-warning mx-2 nowrap">Register</a>
                    <a href="{% url 'login' %}" class="btn btn-outline-warning mx-2 nowrap" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-person-check-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                  d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                            <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                        </svg>
                        Log In</a>
                {% endif %}

                <a href="{% url 'store:cart_summary' %}" class="btn btn-warning mx-2 nowrap" type="button"
                   role="button">
                    <span class="badge badge-pill red"> </span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-cart2" viewBox="0 0 16 16">
                        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"></path>
                    </svg>
                    Cart
                </a>
            </div>
        </div>
</div>
</nav>


<div style="margin-top:70px">
    {% block content %}

    {% endblock %}
</div>
</div>
</body>
</html>

templates/dashboard_with_pivot.html
<head>
  <meta charset="UTF-8">
  <title>Dashboard with Flexmonster</title>
  <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <link rel="stylesheet" href="https://cdn.flexmonster.com/demo.css">
</head>
<body>
<div id="pivot-table-container" data-url="{% url 'pivot_data' %}"></div>
<div id="pivot-chart-container"></div>



function processData(dataset) {
    var result = []
    dataset = JSON.parse(dataset);
    dataset.forEach(item => result.push(item.fields));
    return result;
}
$.ajax({
    url: $("#pivot-table-container").attr("data-url"),
    dataType: 'json',
    success: function(data) {
        new Flexmonster({
            container: "#pivot-table-container",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 430,
            toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data)
                },
                slice: {}
            }
        });
        new Flexmonster({
            container: "#pivot-chart-container",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 430,
            //toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data)
                },
                slice: {},
                "options": {
                    "viewType": "charts",
                    "chart": {
                        "type": "pie"
                    }
                }
            }
        });
    }
});


{#Add it to the dataSource property of the report:#}
{##}
{#mapping: {#}
{#    "product_category": {#}
{#        "caption": "Product Category",#}
{#        "type": "string"#}
{#    },#}
{#    "payment_method": {#}
{#        "caption": "Payment Method",#}
{#        "type": "string"#}
{#    },#}
{#    "shipping_cost": {#}
{#        "caption": "Shipping Cost",#}
{#        "type": "number"#}
{#    },#}
{#    "unit_price": {#}
{#        "caption": "Unit Price",#}
{#        "type": "number"#}
{#    }#}
{#}#}
</body>

templates/design_inspiration.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div class="container mx-25">
        <div class="row row-cols-2 row-cols-sm-2 row-cols-md-3 g-3 mx-2 my-2">

            <div class="col-md-3 ">
                <div class="h-100 p-5 bg-white border rounded-3 text-center">
                    <h4> Design to play </h4>

                    <a href="/media/PDF/rafa-kids-lookbook-lowres.pdf" class="btn btn-outline-warning" role="button"
                       data-bs-toggle="button"> Inspirational Lookbook</a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="h-100 p-5 text-white bg-light rounded-3">
                    <img src="/media/images/Rafa-kids-lookbook01W-800x400.jpg" style="max-width:95%">
                </div>
            </div>

        </div>


        <div class="row row-cols-2 row-cols-sm-2 row-cols-md-3 g-3 mx-2 my-2">
            <div class="col-md-3 ">
                <div class="h-100 p-5 bg-light border rounded-3 text-center">
                    <h4> Shelf collection
                    </h4>

                    <a href="/media/PDF/Rafa-kids-lookbook_shelf.pdf" class="btn btn-outline-warning" role="button"
                       data-bs-toggle="button"> Inspirational Lookbook</a>

                </div>
            </div>
            <div class="col-md-9">
                <div class="h-100 p-5 text-white bg-light rounded-3">
                    <img src="/media/images/Rafa-kids-lookbook02W-800x400.jpg" style="max-width:95%">
                </div>
            </div>
        </div>

        <div class="row row-cols-2 row-cols-sm-2 row-cols-md-3 g-3 mx-2 my-2">
            <div class="col-md-3">
                <div class="h-100 p-5 bg-light border rounded-3 text-center">
                    <h4> Bench collection
                    </h4>

                    <a href="/media/PDF/Rafa-kids-lookbook_bench.pdf" class="btn btn-outline-warning" role="button"
                       data-bs-toggle="button"> Inspirational Lookbook</a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="h-100 p-5 text-white bg-light rounded-3">
                    <img src="/media/images/Rafa-kids-lookbook03-800x400.jpg" style="max-width:95%">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/furniture.html
{% extends "base.html" %}
{% load static %}

{% block title %}Furniture{% endblock %}


{% block content %}
    <div class="container mx-25">
        <div class="row row-cols-3 row-cols-sm-2 row-cols-md-3 g-3 mx-2 my-2">
            {% for category in categories %}
                {% if not category.parent %}

                    {#                    <div class="col">#}
                    {#                <div class="card shadow-sm">#}
                    {#                    <img src="{{ product.image.url }}">#}
                    {#                    <div class="card-body">#}
                    {#                        <p class="card-text"> {{ product.title }}.</p>#}
                    {#                        <p class="card-text"> Price: {{ product.price }} € </p>#}
                    {#                        <div class="d-flex justify-content-between align-items-center">#}
                    {#                            <div class="btn-group">#}
                    {#                                <a href="{% url 'store:product_detail' product_slug=product.slug %}" type="button"#}
                    {#                                   class="btn btn-sm btn-outline-warning">View details</a>#}
                    {#                            </div>#}
                    {##}
                    {#                            <button type="button" class="btn btn-sm btn-warning">#}
                    {#                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"#}
                    {#                                     class="bi bi-cart2" viewBox="0 0 16 16">#}
                    {#                                    <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"></path>#}
                    {#                                </svg>#}
                    {#                                Add to cart#}
                    {#                            </button>#}
                    {#                        </div>#}
                    {#                    </div>#}
                    {#                </div>#}
                    {#            </div>#}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {{ category.name }}
                        </a></li>
                {% endif %}

            {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}Home{% endblock %}


{% block content %}





        <div id="carouselExampleIndicators" class="carousel slide mx-3" data-bs-ride="carousel">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
                        aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                        aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                        aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3"
                        aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4"
                        aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="5"
                        aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="6"
                        aria-label="Slide 3"></button>

            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="/media/images/Rafa-kids-A-teen-bed-banner-1.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="/media/images/Rafa-kids-bench-fits-everywhere-banner.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="/media/images/Rafa-kids-FA-bed-set-for-siblings.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="/media/images/Rafa-kids-FA-set-new-white-BANNER.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="/media/images/Rafa-kids-H-wardrobe-banner.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="/media/images/Rafa-kids-H-WARDROBE-storage-for-children-BNR.jpg" class="d-block w-100"
                         alt="...">
                </div>
                <div class="carousel-item">
                    <img src="/media/images/Rafa-kids-natural-black-toddler-room-banner.jpg" class="d-block w-100"
                         alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>


        <div class="row align-items-md-stretch mt-2">
            <div class="col-md-6">
                <div class="h-100 p-5 text-white bg-dark rounded-3">
                    <img src="/media/images/Rafa-kids-952x1280.jpg" style="max-width:95%">
                </div>
            </div>
            <div class="col-md-6">
                <div class="h-100 p-5 bg-light border rounded-3 ">

                    <p> Rafa-kids originated from the shared dream of two architects. People, who strive for the best in
                        whatever they do, put all their soul and energy into it. Agata takes care of the aesthetic side
                        of the designs and Arek is the technical brain of the duo. Because of our different interests
                        and skills, we discuss all the designs thoroughly and analyse them in a long working process. We
                        like it a lot!</p>
                    <p class="fst-italic text-warning "> We understand parents because we are parents.</p>
                    <p> The world of designing for children opened up to us after the arrival of our two sons, Frank and
                        Robert. We wanted to design high quality and good looking products for them. That is how the
                        first bed for our older son was created. After making it we received so many nice reactions and
                        requests that we decided to realize our dream of starting our own company.</p>

                </div>
            </div>
        </div>

        <div class="row align-items-md-stretch mt-2 ">

            <div class="col-md-6">
                <div class="h-100 p-5 bg-light border rounded-3">

                    <p> We are in love with modern and minimal aesthetic. In our own home, we try to keep things simple
                        with
                        not much furniture and products. This is what we also seek for in designing our collection – to
                        create timeless items that encourage children’s creativity and their eagerness to play.</p>
                    <p class="fst-italic text-warning"> The biggest inspiration for us are our children.</p>
                    <p> Our collection grows together with our boys, and each product comes from personal need. For
                        example
                        Frank sleeps in the bunk bed and he loves to read there. Each evening he used to throw his books
                        on
                        the floor before sleep! There was also not enough space for a night lamp next to the bed. We
                        needed
                        to do something about it. That’s how the small S shelf from our new collection was born.</p>
                    <p></p>
                    <p>We would like to develop Rafa-kids further in the coming years and expand our collection with new
                        beautiful designs. Since our brand grows together with our kids, we hope to create more products
                        for older children, probably also for teenagers.</p>
                    <p> By keeping in touch with our clients, we hope to meet more parent like us – those who look for
                        playful and beautiful designs for their kids, that will last for many years. So, feel welcome to
                        contact us and let us know if you have any questions about our products! We are always here to
                        help you choose and decide.</p>
                </div>

            </div>

            <div class="col-md-6">
                <div class="h-100 p-5 text-white bg-dark rounded-3">
                    <img src="/media/images/Rafa-kids-owners.jpg" style="max-width:95%">
                </div>
            </div>

        </div>
{% endblock %}